### ISSUE TITLE
can you release training code? thank you very much!

### ISSUE THREAD

**Issue by rentju** [jialee93/Traffic_Sign_Recognition_Efficient_CNNs#11]
for the sub-optimal network weight , mAP is just 0.75 ,how to reach to 84.5% mAP in your paper?

**Comment by jialee93** [comment]
The system was not an end-to-end one. We refined the bounding boxes via post-processing (adaptive color segmentation + shape fitting). Some false negatives can be removed after the step of localization refinement.
According to our inner version though a long time ago, one trick is that we can try train two RPN using the same backbone: one for extra dataset and the other for GTSDB (also we should balance the samples from different dataset). After that, we fine-tuned the detector only on the GTSDB dataset.
