### ISSUE TITLE
weights setting is confusing.

### ISSUE THREAD

**Issue by marshellhu** [jialee93/Traffic_Sign_Recognition_Efficient_CNNs#9]
I have met with a problem with test:

> platform win32 -- Python 3.6.7, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: E:\Users\Yangxx\Traffic_Sign_Recognition_Efficient_CNNs-master\mobilenet_frcnn_detector
Windows fatal exception: code 0xc0000374

> Current thread 0x00002c78 (most recent call first):
> 
>   File "D:\program\Users\envs\Keras208\lib\site-packages\h5py\_hl\attrs.py", line 79 in __getitem__
>   File "D:\program\Users\envs\Keras208\lib\site-packages\keras\engine\topology.py", line 3067 in load_weights_from_hdf5_group_by_name
>   File "D:\program\Users\envs\Keras208\lib\site-packages\keras\engine\topology.py", line 2570 in load_weights
>   File "E:\Users\Yangxx\Traffic_Sign_Recognition_Efficient_CNNs-master\mobilenet_frcnn_detector\test_frcnn.py", line 173 in <module>
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\assertion\rewrite.py", line 140 in exec_module
>   File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 971 in _find_and_load
>   File "D:\program\Users\envs\Keras208\lib\site-packages\py\_path\local.py", line 701 in pyimport
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\python.py", line 501 in _importtestmodule
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\python.py", line 433 in _getobj
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\python.py", line 256 in obj
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\python.py", line 449 in _inject_setup_module_fixture
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\python.py", line 436 in collect
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\runner.py", line 247 in <lambda>
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\runner.py", line 220 in from_call
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\runner.py", line 247 in pytest_make_collect_report
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\callers.py", line 187 in _multicall
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\manager.py", line 86 in <lambda>
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\manager.py", line 92 in _hookexec
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\hooks.py", line 286 in __call__
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\runner.py", line 363 in collect_one_node
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 701 in genitems
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 476 in _perform_collect
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 437 in perform_collect
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 244 in pytest_collection
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\callers.py", line 187 in _multicall
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\manager.py", line 86 in <lambda>
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\manager.py", line 92 in _hookexec
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\hooks.py", line 286 in __call__
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 234 in _main
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 191 in wrap_session
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\main.py", line 228 in pytest_cmdline_main
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\callers.py", line 187 in _multicall
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\manager.py", line 86 in <lambda>
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\manager.py", line 92 in _hookexec
>   File "D:\program\Users\envs\Keras208\lib\site-packages\pluggy\hooks.py", line 286 in __call__
>   File "D:\program\Users\envs\Keras208\lib\site-packages\_pytest\config\__init__.py", line 78 in main
>   File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pycharm\_jb_pytest_runner.py", line 31 in <module>
> 
> Process finished with exit code -1073740940 (0xC0000374)
> Empty test suite.
> 

It seems like the weights setting gets wrong, would you mind to give me some help?

The last line in the config.py gives the information about hdf5 file. Where did it come from? How can I get it? Thank you.

**Comment by jialee93** [comment]
Please refer to this  [README file](https://github.com/jialee93/Traffic_Sign_Recognition_Efficient_CNNs/blob/master/Detection/mobilenet_frcnn_detector/README.md):
An avaible pre-trained model of our detecor can be download from: Link: https://pan.baidu.com/s/1Wnsxdcxx8oQ-2B4xhQ08ag Password: gnxe
